# Generated by Django 4.1.5 on 2023-01-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email_site',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
    ]
