# Generated by Django 4.1.5 on 2023-01-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contacts_maps_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('question', models.TextField(verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Обратные свяьи',
                'verbose_name_plural': 'Обратную связь',
            },
        ),
    ]
