# Generated by Django 4.1.5 on 2023-01-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_detail',
            options={'verbose_name': 'Обратную связь', 'verbose_name_plural': 'Обратные связьи'},
        ),
        migrations.RenameField(
            model_name='contact_detail',
            old_name='question',
            new_name='message',
        ),
    ]
