# Generated by Django 4.1.5 on 2023-01-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_tour', models.ImageField(upload_to='Tours', verbose_name='Фотография тура')),
                ('name_tour', models.CharField(max_length=255, verbose_name='Название тура')),
                ('description_tour', models.TextField(verbose_name='Описание тура')),
                ('time_tour', models.CharField(max_length=255, verbose_name='Время тура')),
                ('price_tour', models.CharField(max_length=255, verbose_name='Стоимость тура')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='TourDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tour', models.CharField(max_length=255, verbose_name='Тип тура')),
                ('group_size_tour', models.CharField(max_length=255, verbose_name='Размер группы')),
                ('first_image_tour', models.ImageField(upload_to='tours_image')),
                ('second_image_tour', models.ImageField(upload_to='tours_image')),
                ('destination_tour', models.CharField(max_length=255, verbose_name='Место назначения')),
                ('depature_tour', models.CharField(max_length=255, verbose_name='Отъезд')),
                ('departure_time_tour', models.CharField(max_length=255, verbose_name='Время отправления')),
                ('return_time_tour', models.CharField(max_length=255, verbose_name='Время возврата')),
                ('included_tour', models.TextField(verbose_name='Включено')),
                ('excluded_tour', models.TextField(verbose_name='Исключенно')),
                ('accommodation_tour', models.CharField(max_length=255, verbose_name='Оценка жилья')),
                ('transport_tour', models.CharField(max_length=255, verbose_name='Оценка транспорта')),
                ('comfort_tour', models.CharField(max_length=255, verbose_name='Оценка комфорта')),
                ('hospitality_tour', models.CharField(max_length=255, verbose_name='Оценка гостеприимства')),
                ('food_tour', models.CharField(max_length=255, verbose_name='Оценка еды')),
                ('toures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourse', to='tours.tours', verbose_name='Туры')),
            ],
            options={
                'verbose_name': 'Информация про тур',
                'verbose_name_plural': 'Информация про туры',
            },
        ),
    ]
