# Generated by Django 4.1.5 on 2023-01-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='accommodation_tour',
            field=models.CharField(default=1, max_length=255, verbose_name='Оценка жилья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='comfort_tour',
            field=models.CharField(default=1, max_length=255, verbose_name='Оценка комфорта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='departure_time_tour',
            field=models.CharField(default=1, max_length=255, verbose_name='Время отправления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='depature_tour',
            field=models.CharField(default=1, max_length=255, verbose_name='Отъезд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='destination_tour',
            field=models.CharField(default=1, max_length=255, verbose_name='Место назначения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='excluded_tour',
            field=models.TextField(default=1, verbose_name='Исключенно'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='first_image_tour',
            field=models.ImageField(default=1, upload_to='tours_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='food_tour',
            field=models.CharField(default=1, max_length=255, verbose_name='Оценка еды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='group_size_tour',
            field=models.CharField(default=1, max_length=255, verbose_name='Размер группы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='hospitality_tour',
            field=models.CharField(default=1, max_length=255, verbose_name='Оценка гостеприимства'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='included_tour',
            field=models.TextField(default=1, verbose_name='Включено'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='return_time_tour',
            field=models.CharField(default=1, max_length=255, verbose_name='Время возврата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='second_image_tour',
            field=models.ImageField(default=1, upload_to='tours_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='transport_tour',
            field=models.CharField(default=1, max_length=255, verbose_name='Оценка транспорта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tours',
            name='type_tour',
            field=models.CharField(default=1, max_length=255, verbose_name='Тип тура'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TourDetail',
        ),
    ]
