# Generated by Django 4.1.5 on 2023-01-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='name_tour',
            new_name='title',
        ),
    ]
