# Generated by Django 4.1.5 on 2023-01-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_rename_name_tour_tours_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='title',
            new_name='name',
        ),
    ]
