# Generated by Django 4.1.5 on 2023-01-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_rename_title_tours_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='name',
            new_name='title',
        ),
    ]
