# Generated by Django 4.1.5 on 2023-01-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='about', verbose_name='Первая фотография о нас')),
                ('image_2', models.ImageField(upload_to='about', verbose_name='Вторая фотография о нас')),
                ('video', models.URLField(verbose_name='Ссылка на видео')),
                ('image_video', models.ImageField(upload_to='about', verbose_name='Обложка для видео')),
                ('about', models.TextField(verbose_name='О нас и что мы предлагаем')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='AboutNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oput', models.CharField(max_length=255, verbose_name='Oпыт')),
                ('person', models.CharField(max_length=255, verbose_name='Сотрудники')),
                ('client', models.CharField(max_length=255, verbose_name='Клиентов')),
            ],
            options={
                'verbose_name': 'Мы в цифрах',
                'verbose_name_plural': 'Мы в цифрах',
            },
        ),
    ]
