# Generated by Django 4.1.5 on 2023-01-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(default=1, max_length=255, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
