# Generated by Django 4.1.5 on 2023-01-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_blog_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_time',
        ),
    ]
