# Generated by Django 4.1.5 on 2023-01-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_name',
            new_name='title',
        ),
    ]
