# Generated by Django 4.1.5 on 2023-01-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_blog_name_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_type',
            new_name='type',
        ),
    ]
