# Generated by Django 4.1.5 on 2023-01-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_blog_description_blog_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='blog_description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='blog_image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='time',
            new_name='blog_time',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='type',
            new_name='blog_type',
        ),
    ]
