# Generated by Django 4.1.5 on 2023-01-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_ticket', models.ImageField(upload_to='tickets', verbose_name='Фотография')),
                ('name_ticket', models.CharField(max_length=255, verbose_name='Название')),
                ('description_ticket', models.TextField(verbose_name='Описание')),
                ('first_image', models.ImageField(upload_to='tickets', verbose_name='Первая дополнительная фотография')),
                ('second_image', models.ImageField(upload_to='tickets', verbose_name='Вторая дополнительная фотография')),
                ('address_ticket', models.CharField(max_length=255, verbose_name='Место назначения')),
                ('departur_time', models.CharField(max_length=255, verbose_name='Время отправления')),
                ('return_time', models.CharField(max_length=255, verbose_name='Время возврата')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
