# Generated by Django 4.1.5 on 2023-01-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='price_ticket',
            field=models.CharField(default=1, max_length=255, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
