# Generated by Django 4.1.5 on 2023-01-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_site', models.ImageField(upload_to='logo_site', verbose_name='Логотип')),
                ('name_site', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('description_site', models.TextField(verbose_name='Описание сайта')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
