# Generated by Django 4.1.5 on 2023-01-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_ticket_tours_travel_ticket_toursdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_toursdetail',
            name='countres',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
        migrations.DeleteModel(
            name='Ticket_tours',
        ),
        migrations.DeleteModel(
            name='Ticket_toursDetail',
        ),
    ]
