# Generated by Django 4.1.5 on 2023-01-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_image', models.ImageField(upload_to='team', verbose_name=' Фотография')),
                ('team_name', models.CharField(max_length=255, verbose_name='Ф.И.О')),
                ('team_work', models.CharField(max_length=244, verbose_name='Должность')),
                ('team_email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('team_instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('team_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('team_whatsapp', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Наша команда',
                'verbose_name_plural': 'Наша команда',
            },
        ),
    ]
