# Generated by Django 4.1.5 on 2023-01-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_image', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Галлерея',
            },
        ),
    ]
