# Generated by Django 4.1.5 on 2023-01-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страну',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel', models.CharField(max_length=255, verbose_name='Тип путешествия')),
            ],
            options={
                'verbose_name': 'Тип путешествия',
            },
        ),
        migrations.CreateModel(
            name='Ticket_toursDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('countres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countres', to='index_search.ticket_tours', verbose_name='Страны')),
            ],
            options={
                'verbose_name': 'Города',
            },
        ),
    ]
